fix: all checks double quoted

diff --git a/bin/heroku-update-env b/bin/heroku-update-env
--- a/bin/heroku-update-env
+++ b/bin/heroku-update-env
@@ -3,15 +3,21 @@
 FILE_NAME=$1
 APP_NAME=$2
 
-if [ -z $FILE_NAME ]; then
+if [ -z "$FILE_NAME" ]; then
   echo "Missing file name"
   exit 1
 fi
 
-if [ -z $APP_NAME ]; then
+if [ -z "$APP_NAME" ]; then
   echo "Missing app name!"
   exit 1
 fi
+
+if [[ ! -f "$FILE_NAME" ]]; then
+  echo "Missing '~/bin/.env' file"
+  exit 1
+fi
+
 
 cat $FILE_NAME | xargs -p heroku config:set --app $APP_NAME
 
